[package]
name = "gong_rsa-25"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
modular = "1.0.0"
num-primes = "0.2.0"
num-traits = "0.2"
num-bigint = "0.4"

sha2 = "0.10.9"
schnorr-rs = "0.2.0"
hex = "0.4.3"
